name: Deploy Driver App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend/driver-app
          push: true
          tags: 184073611589.dkr.ecr.us-east-1.amazonaws.com/driver-app:latest

      - name: Deploy to AWS ECS Fargate
        run: |
          aws ecs update-service --cluster afourathon-cluster --service driver_app_service --force-new-deployment
